### ISSUE TITLE
nc mouse compatibility: missing has_mouse

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#109]
For details *and the actual implementation* - see https://github.com/wmcbrine/PDCurses/issues/62.

Please merge this change (and other non-conflicting ones if possible).
Big please: create a release.

**Comment by Bill-Gray** [comment]
OK,  we have a 4.1.0 release,  which includes the new `has_mouse()`... let me know if you see issues/have thoughts for improvement.

This is the first release since 2017 September 12.  I will concede that releases should occur at least _slightly_ more often than this.  As best I can tell,  the only downside to creating a release is that if you do it too often,  GitHub will consider it to be "abuse".  I think we're a long way from that being a problem.

Obviously,  I've not been doing much on this fork for a while.  During that time,  William McBrine has moved the upstream version along nicely.  I like what he's done with SDL2 and the new fork-less X11 version.  The Windows console version has a variety of fixes for colors,  user resizing,  lines (under/over/left/right) and so forth.  Unfortunately,  we're reaching the point where getting what I've done pulled in by William,  or getting his work into this fork,  are both looking to be really huge jobs.  Bits and pieces have made their way back and forth,  but that's about it.

I think this is regrettable.  A PDCurses that had the WinGUI and VT platforms,  full RGB color,  _and_ the wonders in the upstream fork would be a truly formidable thing.
