### ISSUE TITLE
Merging upstream improvements

### ISSUE THREAD

**Issue by Bill-Gray** [Bill-Gray/PDCurses#110]
This is a follow-on to @GitMensch's [suggested plan for re-joining this fork with the "original" @wmcbrine version](https://github.com/wmcbrine/PDCurses/issues/64),  which may have been motivated in part by [comments I made about such a merger a few days earlier](https://github.com/Bill-Gray/PDCurses/issues/109).  I held off on commenting on the plan,  thinking I really ought to offer William the first shot at it.  It is,  after all,  his project.

Conversation on that issue is now limited to collaborators and it's been marked 'closed' (which is why I opened an issue here instead).  I don't think conversation has been cut off on other issues,  so I'll assume that William's attitude toward a merger is not just "no",  but "hell,  no".

I will admit to some disappointment in this.  Quite a bit of code has worked its way back and forth between this fork and the @wmcbrine version,  but it would have simplified things if we just had one version combining the improvements here (64-bit `chtype`s with complete Unicode support and more attributes,  the VT and WinGui platforms,  etc.) with the upstream improvements.  William has done really nice things with the Windows console and SDL2 platforms,  and I like the `x11new` platform;  having to deal with the forked processes and communication between them really made the code more complicated than one would wish.  I never really understood much of what it does.

If my fork isn't going to be merged upstream,  I think we have to reluctantly consider going the other way and merging William's work here instead.  @GitMensch,  thanks for pointing out [a way to pull a directory in using a 'merge filter' to preserve its history](https://bneijt.nl/blog/post/merge-a-subdirectory-of-another-repository-with-git/).  As you may have gathered,  my knowledge of Git innards is somewhat limited;  I had no idea you could do that,  and had not looked forward to possibly losing a lot of commit history.  If I'm understanding it correctly,  this ought to be a big help.

I'm thinking that we could pull in William's `x11new` branch "as is" using this method.  We'd then get it to work in this fork by adding in 64-bit `chtype`s and so on.    We might rename the current `wincon` directory to,  say,  `wincon_old`,  and then similarly import and fix up William's `wincon`.  And likewise with the SDL2 platform.  (And then delete `wincon_old` and `sdl2_old`.)

I _think_ that with those three platforms essentially pulled in and working,  we would have achieved the goal of combining the best of the upstream version with the best of this fork.  Any comments?  (@wmcbrine,  I sense you'd rather have nothing to do with any of this... still,  I'd be interested in any thoughts you have on it.)

**Comment by GitMensch** [comment]
> This is a follow-on to @GitMensch's suggested plan for re-joining this fork with the "original" @wmcbrine version, which may have been motivated in part by comments I made about such a merger a few days earlier.

Actually we brought up this topic more than once and I hoped to get a final "yes, let's do this" with the "new" point "whenever in question, follow upstream". One thing we will have soon is also a conflicting version (at least if @wmcbrine goes to 4.0 after 3.9).
In the last years both repos had a (longer or shorter) time where they looked abandoned by the maintainers. Having two official maintainers (with a rule "if in question follow William") would be a way to prevent this.

> I held off on commenting on the plan, thinking I really ought to offer William the first shot at it. It is, after all, his project.

I've thought so and it was a good decision.

>  I don't think conversation has been cut off on other issues, so I'll assume that William's attitude toward a merger is not just "no", but "hell, no".

That's my understanding, too.

> I will admit to some disappointment in this.

Me, too.

But I come with a last resort (which would be good to have been discussed at the now closed issue, but that's the way it is)... Not sure if William gets a notification when mentioned in this repo, so I'll create another issue over at his repo if we don't read anything from him here within the next days [as this issue is created currently here - @Bill-Gray please comment after having thought of this]):

@wmcbrine & @Bill-Gray What do you you think of following the proposed plan not in master but in a new branch "Bill-Gray" or "pdcursesx"?
Bill (and possibly me) will only get in as developers and make an oath to not commit or accept PR into master on our own.

This would have the following benefits:
* The real work would be in one repository, over @wmcbrine .
* This repo *could* be recreated as a fork of that branch once we are finished doing the work to the new branch.
* All upcoming merges between the branches (or the two repos) will be much easier, as both would have a much more common history and less conflicts.
* Releases from "pdcursesx" would be possible by @wmcbrine from this branch or by @Bill-Gray from here (depending on whatever we agree).
* PR to "general" issues can be handled at both places and could be simply merged after they are in.

If this doesn't work out I suggest to make an agreement (including this in the "implementing" docs) that William's original stays at 3.x forever and Bill's fork stays at 4.x forever (in which cases we would adjust the internal package name here to pdcurses4).

**Comment by Bill-Gray** [comment]
I'd go along with a 'pdcursesx' or similar branch.

I'm quite flexible about how a merger occurs.  (Though I'm glad you've put some effort into figuring out how we'd preserve commit history.)  My main goal would be simply to _have_ a merged version in the first place.  At present,  pulling in the upstream changes requires a good bit of effort.  Being lazy,  I'd like to just see William's changes popping up automatically for me... which,  if we were well and truly merged,  would be the case.

On the bright side,  a bit of investigation yesterday suggests to me that importing William's `x11new`,  `wincon`,  and `sdl2` platforms may be relatively straightforward.  (This part being true regardless of whether we follow your plan,  or instead just pull those directories into the Bill-Gray fork.)  We'd have to adopt some of William's changes into my fork which are perfectly reasonable,  such as adding a `set_bold` function and making `termattrs` behave correctly.  I _think_ that those three platforms would then compile and work (as long as you used 32-bit `chtype`s).

We'd then have to add 64-bit `chtype`s to them and add full Unicode compliance,  overlining/strikeout/dimming,  full RGB coloring,  double and triple mouse clicks,  etc.  Tedious,  but not particularly hard.

Regarding version numbers,  I could see us also agreeing that William would use 3.x,  5.x, 7.x, ... and our fork would stick to even major version numbers.

**Comment by wmcbrine** [comment]
Sigh. OK, let's start with a relatively easy one: "full RGB coloring". This is a good example of something I consider a misfeature. It breaks everything about the curses color model, but more importantly, it's a bad design. You devote fully half of your 64-bit chtype to this system, yet for all that used space, you still get a rather poor range of colors, with only five bits per channel. In your `newtest`, the sample lines meant to illustrate this feature by changing colors every cell actually only change every two or three cells -- a total of 32 color combinations per line -- because that's the limit of your resolution.

Now, I don't want to just say "that's bad" without offering something better; so, I rewrote your gradient test with standard curses calls and added it to the Color Test in `testcurs`. This version actually changes colors with every cell. Only problem: It needs 200-some color pairs to do that, and 400-odd colors. So, I expanded `COLORS` for the capable platforms (SDL, X11, and wincon). With `COLOR_PAIRS` still limited to 256 by the 32-bit chtype, if each pair had a unique foreground and background, we could have 512 colors. I added them on to the end so the pre-defined colors could be left alone, for 768 colors total. This is about the limit of what can usefully be done with a 32-bit chtype. (If I limited it to 32 combinations per line, I'd only need 96 pairs and 192 colors, which would fit in the 256-color range.)

And it's arguably a bit of a cheat, since I still barely have enough colors to cover the three lines. But my tentative design for a 64-bit chtype would extend the color pairs to 16 bits, which would suffice to cover a 256x128 screen with unique colors. (Then I'd have 16 bits for attributes -- you *need* 15 bits to have unique flags for all of the X/Open-specified flags, which is another problem with your chtype, with only 12 attribute bits -- and 32 for the character, which is admittedly more than needed, but it does align neatly.)

More later...

**Comment by GitMensch** [comment]
@wmcbrine thank you for contributing to this discussion.
For this first part - I'd personally would be fine if:

* the color support would be increased with 32bit chtype as done in your repo already (@Bill-Gray I assume you are fine to copy the changes over here?)
* the 64bit chtype would be done different (possibly "correct") and be made "request only" (it is currently the default here)

Especially if this would solve issues that otherwise would lead to a total split.
@wmcbrine Obviously it is good when you directing chtype changes - as far as I know you just were not available when it was done. Waiting for more.

**Comment by Bill-Gray** [comment]
OK.  This sounds to me as if the fork will remain a fork.  To be honest,  I've been hoping you'd slurp the changes into your version and I'd fade away.  (I have various "day job" commitments at present,  which is why I've done little on PDCurses of late.)  I can definitely understand your wanting to avoid taking on my code,  especially given your dislike of the decisions I've made,  of which it sounds as if RGB is but the tip of an enormous iceberg.

Still,  thanks for the comments;  it gives me an idea of some of the upstream changes you've got in mind.

I will note that I've done many things that break traditional Curses models,  including full RGB.  They're _options_.  Want to use the traditional color model?  Don't set `A_RGB`.  Don't want a blinking vertical caret for a cursor?  Just stick to the traditional values sent to `curs_set()`.

Fair point about getting all the X/Open flags,  though.  Again,  I can say that those wanting that level of backward compatibility won't be setting 'A_RGB' anyway,  so that for them,  those bits _will_ be available.  (You can set `A_RGB` and have 30 color bits and twelve attribute bits,  or omit it and have a 16-bit "traditional" color pair index and 26 attribute bits.)  Set `A_RGB`,  and you'll have to settle for a still rich,  but not X/Open compatible,  set of attribute flags... but you knew that when you set `A_RGB'.

I considered a scheme such as the one you suggest,  of allowing so many colors and color pairs that you could be reasonably confident of having one per character cell (though I note that getting windows with more than 32K cells is easily done;  I just opened an xterm to 971x224.)  I find the idea of setting a color pair per cell somewhat repulsive,  but have to agree that it's the only way I can see to get eight bits per channel for every cell.  I expect I'll allow for 64K colors and color pairs,  just to maintain some compatibility with your fork.

But I figured (and still think that) five bits per channel are sufficient _for this purpose_.  We're working on character-based interfaces here,  not imagery.  I wanted to be able to show,  say,  light cyan leaning toward yellow text on a burnt sienna background;  for that purpose,  being able to specify colors to five bit precision lets you get "light cyan leaning on yellow".  If you really wanted other text to be "light cyan leaning heavily to yellow",  you might need to use your scheme.  But I find the value of that to be doubtful.

**Comment by wmcbrine** [comment]
> They're options. ... You can set A_RGB and have 30 color bits and twelve attribute bits, or omit it and have a 16-bit "traditional" color pair index and 26 attribute bits.

What do you mean? There's nothing like that in your code. COLOR_PAIRS never exceeds 256.

**Comment by Bill-Gray** [comment]
"...`COLOR_PAIRS` never exceeds 256."

True.  I should have been clearer about the fact that I've been _considering_ bumping up `COLOR_PAIRS` for some time,  but haven't actually done so yet.  At present,  you can set `A_RGB` and have 30 color bits,  or omit it and have eight color pair index bits and 22 bits go completely to waste.  But nothing would prevent us from having more bits used for the color pair index.  Having 2^30 possible color pairs seems _really_ silly to me,  and would mean sacrificing possible X/Open flags.  2^16 pairs ought to be enough for anybody.

I hadn't gone past 256 color pairs for several reasons,  one of which was memory : I didn't want to allocate space for 65536 color pairs when it was unlikely anyone would use them.  (And I still doubt that anyone would set that many pairs;  I think most people would use the RGB method instead.  Yes,  it's not compatible with traditional curses.  But 65536 color pairs would also be incompatible with any traditional curses of which I'm aware.  And yes,  you only get five bits per channel... but as mentioned above,  I don't see that as significant for a text-based application.)

Worrying about allocating a mere 256K for the color pair table,  plus another half meg or so for the colors,  may be showing my age (the first computer I worked on had 4K of memory.)  But it occurs to me that I can still initially allocate a table for only 256 color pairs.  Then,  if somebody calls `init_pair()` with a pair number greater than 255,  I'll reallocate the table to expand it.  With suitable logic to provide the default white-on-black values if somebody calls `pair_content()` for a currently unallocated index.  And similar logic for the colors.

This should _not_ really require very much code.  And I accept that the split in our forks is permanent at this point,  but it'll simplify my life if I maintain some compatibility with what you're doing.

Incidentally,  you mentioned that the RGB scheme uses almost half of the 64-bit `chtype` for color.   It does seem wasteful.  But I still haven't heard a better idea as to what to do with all those bits.  (Noting that I'm still able to get the larger color pair range and the X/Open bits,  despite the availability of an RGB color option.)

**Comment by GitMensch** [comment]
The 64bit chtype and the extended color range is obviously something that needs deeper thoughts, I'd like to open an issue about this at a different time, as it looks it won't be "solved" anytime soon.

@wmcbrine  said:
> More later...

... so let's go to the topic. What do you think would need correction in this fork other than the 64bit chtype and "the color issue"?

Especially - What do you think about getting the wingui and vt ports and the "ncurses-demos" into upstream master?

What about the support (with 32bit chtype) of combining + fullwidth characters + Unicode values <= 0xffff (all in wide mode), triple clicks , bold and italic fonts, blinking text?

**Comment by Bill-Gray** [comment]
"...What about the support (with 32bit chtype) of combining + fullwidth characters + Unicode values <= 0xffff (all in wide mode), triple clicks , bold and italic fonts, blinking text?"

William does have the bold/blinking/italic fonts working.  The `ncurses` demos haven't been brought in yet,  but it's easy to get them to work in the wmcbrine fork.  (Just copy the `ncurses` folder over and `make` or `make WIDE=Y`.  You'll also need to copy `newtest.c` from my `demos` directory to William's... but do a 'git pull' first;  turns out I'd not posted a change made to get around `A_OVERLINE` and `A_STRIKEOUT` attributes not existing in William's version.)

I don't expect William will reverse course and decide to gobble up the changes from this fork.  _Theoretically_,  in an alternative universe where that happened,  he'd take in the changes you mention for WinGUI,  VT,  full Unicode support (minus Unicode >= 64K),  triple clicks,  more mouse buttons,  along with:  blinking/alternative cursor styles;  overlined and struck-out text;  the SLK improvements (clearer code,  more layout options,  ability to change the layout);  and perhaps make some use of the remaining bits for 64-bit `chtype`s,  if they aren't going to go to RGB coloring.  But it seems unlikely that any of these will happen.

Switching to a more realistic scenario,  for this fork to "absorb" the goodies William has provided,  I'd have to add the 'x11new' platform;  increase COLORS and COLOR_PAIRS to 64K;  bring in a shedload of improvements to Windows console resizing and attributes;  and a smaller shedload of SDL2 improvements (many of which this fork has as well,  but the implementation is different).  I don't expect this to happen really soon,  but that's mostly due to lack of time (other commitments);  it shouldn't actually be a huge job.

**Comment by GitMensch** [comment]
@Bill-Gray you're doing an impressive work on merging the upstream changes in while keeping the additions that were available in your fork.
Can you give a rough estimate how far you got already? As soon as the automated builds work again (see #116) and some of your tests do, too, I'd apprechiate release of 4.2.

**Comment by Bill-Gray** [comment]
I think that once we've puzzled out the automated build issues (and,  of course,  assuming no new issues arise),  we're ready to release this as 4.2.  I do have some further changes in mind,  but none that would break binary compatibility.  (If I had such changes in mind,  I'd want to get them all in place before bumping up the minor version number.)
Except for  bug fixes followed by a 4.2 release,  I will do little with this fork for a while,  both because of day-job commitments and because I'd like to give @wmcbrine a chance to decide if this fork is really permanent,  at a point where the merger has been made about as easy as it can be.  I do have some [thoughts for still further improvements](https://www.projectpluto.com/temp/todo.txt) (written mostly to remind me things I'd like to do;  not necessarily of interest to anyone else).  But it'll be a while before I actually work on them.

**Comment by Bill-Gray** [comment]
We appear to be closing in on working automated builds (thanks to @jmalak,  @jwinarske, @GitMensch for tackling this!).  Once that happens,  I think it'll be time for 4.2.0.  There is still much I'd like to do,  but it'd be good to get a release of what we've got... anyone got a reason to hold off?
I've updated `HISTORY.md` and some documentation.  My current plan is to add a mention of automated builds as a "new feature" to `HISTORY.md`,  change the `PDC_VER_*` #defines,  and do a release.

**Comment by GitMensch** [comment]
Yes, please do a new release soon, ideally the CI build works before, but I'd not make this a dependency.

@Bill-Gray can you please check to get the hooks working with Appveyor (again)? Seems the webhook is not configured in GitHub correctly (you find the URL in the Appveyor project settings).

**Comment by Bill-Gray** [comment]
Back when not much progress was happening on automated builds,  I was thinking about just going ahead without them.  It now looks as if success is possible.
I think we're now set with AppVeyor again.  Seems to be generating the same errors :

`C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(2487): error C2118: negative subscript`

**Comment by jwinarske** [comment]
So far it looks like only VS2015 x86 builds are broken.  I suspect it happened when someone updated the cmake version.

[Appveyor build status (Windows)](https://ci.appveyor.com/project/jwinarske/pdcurses-21dj3)
[Travid build status (Mac/Linux)](https://travis-ci.com/github/jwinarske/PDCurses)

@Bill-Gray These are intended to be used as a basic health gate, so before merge to master the build needs to pass, as a minimum.

**Comment by GitMensch** [comment]
Thanks to the last commits the CI builds are all green again. We really should try to keep it that way :-)

Question @jwinarske is it a lot of work to add something outside of cmake to the Travis build? The x11 port comes with a configure script, therefore travis would only need to run `./configure && make && make install` to verify it works (and possibly some x11 headers have to be installed beforehand). It may be run as two jobs, one specifying no compiler (using the system default gcc) and one using `./configure CC=clang`. Do you see an option to add this?

@Bill-Gray can you please check the warnings on the Travis build? It says that some PDCurses functions are not declared ?!?

Concerning the release: We got multiple reports that the colors in GnuCOBOL are borked with PDCurses 4 (compared to all 3.x versions). I fail to remember if there was an intended change before 4.1 or any "fix" that relates to this since 4.1. @Bill-Gray do you have some wisdom to share concerning this issue? [I'd really like to have 4.2 using the colors that previous PDCurses versions had since years].

**Comment by Bill-Gray** [comment]
In re Travis warnings : <a href="https://travis-ci.com/github/Bill-Gray/PDCurses/jobs/338232107#L4906"> this one is an accurately diagnosed flat-out error</a> (should be bitwise ORed,  not logically).  I'm investigating it,  but think that converting || to | really is all that need be done (and thus far,  that appears to be true).
<a href="https://travis-ci.com/github/jwinarske/PDCurses/jobs/338200904#L1868">This warning makes no sense to me.</a>  Looks as if both `PDC_WIDE` and `HAVE_NCURSESW` were defined.  It should be one or the other.
@GitMensch, can you provide more info about these "borked colors"?  First I've heard of it.  I just tried running the wmcbrine version of `testcurs` against ours (for X11),  and the "color test" looked identical.  I could imagine that something more subtle could have slid past me,  though.  (I can think of no good reason for there to have been a change.)

**Comment by GitMensch** [comment]
Concerning the colors I've just got a note that 4.1.1 may have fixed those. Please wait done days for details.

**Comment by GitMensch** [comment]
There was some confusion because 4.2.0 beta has the version info 4.1.1 - it should at least have something like 4.1.990 (or 4.2.0).

**Comment by Bill-Gray** [comment]
Good point.  I've made it 4.1.99.  One reason for the beta was that I assumed I'd make at least one blunder of that ilk.
Aside from changing `PDC_VER_MINOR` to 2, `PDC_VERSION_CHANGE` to 0,  and `PDC_VER_DAY` to the current day,  I think we're ready to push the 'publish release' button.  Anyone see any reason not to do so? @GitMensch, have you confirmed that the colors are actually okay? (That's the only thing I can think of that would cause me to put 4.2.0 on hold.)

**Comment by GitMensch** [comment]
5caa50c33716cbd5314d49ebd40e6f3f69281e0b misses version.mif, but it is good to have it adjusted any way.
We've got more reports in GnuCOBOL about the colors in the beta as being broken (since 4.x), see [the current discussion thread about PDCurses 4 color problems](https://sourceforge.net/p/open-cobol/discussion/help/thread/bc0f3d2ea5). I'd really like to have this solved with 4.2.
The code in GnuCOBOL that produces the colors is found in [screenio.c, lines 235-313](https://sourceforge.net/p/open-cobol/code/HEAD/tree/branches/gnucobol-3.x/libcob/screenio.c#l235) and uses the exact same code (PDCurses provides `color_set()` in general).
@Bill-Gray Is there an option for you to have a look at this please?

**Comment by GitMensch** [comment]
I've recognized one "missing" bit when compared to PDCurses 3.9: `PDC_get_input_fd()`, it may be useful to have a look if it is reasonable to merge it in.

**Comment by GitMensch** [comment]
Updated report:

> Specifically 4.1.1 & CHTYPE=64 - obviously the colours are different (or non existant) in the CHTYPE=32 version of 4.1.1 or 4.2.

So the report (which may be should tracked separately) is that the color settings using color pairs that use the default constants (which worked since years) only works with CHTYPE=64.

**Comment by Bill-Gray** [comment]
[`PDC_get_input_fd()` was deprecated and `#defined` out in William McBrine's latest version.](https://github.com/wmcbrine/PDCurses/commit/48b0c1297529758a10a68aca0f904f90893f165d)
I've opened a new issue #130,  and suggest we move there.
In fact... I'd say we've now merged upstream improvements,  and our improvements aren't going to be merged the other way.  So we might as well close this issue.
