### ISSUE TITLE
Following 'wincon' readme.md leads to compile error with VS2019

### ISSUE THREAD

**Issue by sigmareaver** [Bill-Gray/PDCurses#114]
I'm using Visual Studio Community 2019.

Following the directions to compile the 'wincon' port leads me to an error:

    ..\curses.h(49): fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory

So I'm lead to think that the project isn't setup correctly, or I'm using the wrong nmake? Since 'stdint.h' exists, I guess it's just not being given the correct search path for includes (and maybe libs too).

**Comment by Bill-Gray** [comment]
Hmmm... MS has a long history of implementing standards poorly,  and it took them a _long_ time to get around to implementing `stdint.h` and some other C99 bits.  But it seems to me you ought to have it in VS2019.
If `stdint.h` exists,  but not in the same directory as (say) `stdio.h` et. al.,  that sounds very much as if the `INCLUDE` path is not set up correctly.  Which would seem odd.  But it _is_ MS;  they sometimes do odd things.
I'd recommend trying to actually fix the problem so that `stdint.h` is in the search path,  because you're bound to run into this problem elsewhere.  It's not like it's some obscure include file that you'll never need again (which is why its absence,  20 years after being added to the C standard,  is difficult to fathom).  But a dirty solution would be to `#define NO_STDINT_H` (see `curses.h`).  PDCurses does have to work on elderly compilers,  some of which date back to before 1999,  when `stdint.h` didn't exist anywhere.  So there's a little bit of code to define the very few things that are actually needed on such platforms.  You _could_ just set that `#define` and (I think) finish the compilation.

**Comment by sigmareaver** [comment]
I hate to side track this, but...

I can compile PDCurses into a lib if I turn it into a VS project. However, I'm not certain it's actually working properly. I tried to run the rain demo in a separate project, but it's giving me unresolved external symbol errors.

I will try to add the stdint.h include path to see if I can compile it via the makefile instead, but I'm inexperienced with makefiles.

**Comment by sigmareaver** [comment]
I did this to 'wincon/Makefile.vc':
    INC = -I"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include"
    . . .
    BUILD      = $(CC) $(INC) -I$(PDCURSES_SRCDIR) -c $(CFLAGS) $(CHTYPE_FLAGS) $(DLLOPT) \

It no longer is complaining about 'stdint.h'. Now it is complaining about 'stddef.h'. My problem is I don't know WHICH 'stddef.h' to be using. There's seemingly several included in Visual Studio. See attached image.
![stddef](https://user-images.githubusercontent.com/6249501/66150702-f3577a00-e5d2-11e9-8286-4281799c9c70.png)

**Comment by sigmareaver** [comment]
I'm going to close this since I don't really know what to about the situation. In Visual Studio Community 2019 the only way I've found to use PDcurses successfully is by incorporating the source files directly in my project.
