### ISSUE TITLE
Ugly resizing with WinGUI

### ISSUE THREAD

**Issue by loblolly986** [Bill-Gray/PDCurses#156]
At present, resizing a WinGUI window on a system with the classic Windows visual style and "show window contents while dragging" enabled looks like this:
 
![PDCurses_ugly_resizing](https://user-images.githubusercontent.com/66034630/84068724-6ce00d00-a997-11ea-9ad4-8fd2b42ca9a8.png)

I tried it with the `PDC_DEBUG` environment variable set to a suitable log file, and it reveals that while `KEY_RESIZE` is being correctly added to the key queue with each "step" during the resize, the program isn't allowed to process the key queue until the mouse button is released at the end of the resize (each call to `resize_term(0, 0)` by the program results in an "Incoming: 0 0" message in the log file). An example log file is attached: [pdcdebug.log](https://github.com/Bill-Gray/PDCurses/files/4748027/pdcdebug.log)

I looked at the PDCurses source code but it isn't obvious to me what is preventing the program's `getch()` loop from executing during the resize.

Systems tested: Windows NT 4.0, Windows Vista with classic style.

**Comment by Bill-Gray** [comment]
On both WinME and Win10,  the `KEY_RESIZE`s are stacked up and only sent out when you release the mouse button.  (I could see perhaps sending a single `KEY_RESIZE` when the button is released,  but can come up with no reason to save them up until the mouse button is released.)

On WinGUI on Wine,  and on X11,  VT,  ncurses,  and SDL2,  a `KEY_RESIZE` is sent each time the window is resized (so you get them one after another as the mouse moves)... so,  pretty much the behavior you'd want.

I don't see a good reason for this offhand.  Might be a few days before I can get back to you on this,  I'm afraid... it may be significant that it works properly under Wine,  though I'm not seeing the significance at the moment.

**Comment by GitMensch** [comment]
> On both WinME and Win10, the `KEY_RESIZE`s are stacked up and only sent out when you release the mouse button.

This doesn't match the "Windows NT 4.0" or "Windows Vista" notes above. Does it apply there, too?

> (I could see perhaps sending a single `KEY_RESIZE` when the button is released, but can come up with no reason to save them up until the mouse button is released.)

Me neither :-)

> On WinGUI on Wine, and on X11, VT, ncurses, and SDL2, a `KEY_RESIZE` is sent each time the window is resized (so you get them one after another as the mouse moves)... so, pretty much the behavior you'd want.

Hm, maybe the event got fired too often and should only be fired every n milliseconds? Maybe annotate/blame show a reason why this was stacked?

**Comment by loblolly986** [comment]
It isn't just that `KEY_RESIZE` isn't being "sent out" until the mouse button is released; the program's own code (the `getch()` loop) is preempted altogether. I think I found the reason: https://stackoverflow.com/questions/3102074/win32-my-application-freezes-while-the-user-resizes-the-window

See in particular the answer by nfries88, who implemented "loopless" code to handle sizing and moving operations without pausing one's program, and released it into the public domain on SourceForge. I'm going to try modifying WinGUI to use this. It may or may not need modifications for PDCurses purposes (e.g. to ensure compatibility with all supported Windows versions, or to further optimize its efficiency), but it looks promising.

**Comment by GitMensch** [comment]
@loblolly986 as your other PR is merged now, can I suggest you target this one next?

**Comment by Bill-Gray** [comment]
I made a small fix so that code won't give you a blizzard of `KEY_RESIZE`s.  The only real advantage of this is that if you (say) expand/shrink the window by ten columns,  you'll get one `KEY_RESIZE` event instead of ten.

I'm not all _that_ fussed about the ugliness of the resizing.  On some systems,  you get artifacts while the mouse is dragged;   everything is cleaned up when you release the mouse button at the final size.  But in at least some situations where redraws are slow,  having lots of completely bogus resize events could be a performance issue.

**Comment by GitMensch** [comment]
> The only real advantage of this is that if you (say) expand/shrink the window by ten columns, you'll get one `KEY_RESIZE` event instead of ten.

Was that a wingui only issue?

> But in at least some situations where redraws are slow, having lots of completely bogus resize events could be a performance issue.

I totally agree. Again the question: is this identical in sdlN, xterm, wincon, vt or does the application get a redraw and/or a resize event during resize?

@loblolly986 Does this only happen with the "classic" styles (which seems to be considered obsolete by MS)?

**Comment by Bill-Gray** [comment]
> Was that a wingui only issue?

Yes,  essentially.  With everything else (SDLs,  X11, VT, ncurses),  you get ten `KEY_RESIZE`s... but you get them _as you resized the window_,  with the window's size adjusted properly each time.  With WinGUI,  you only get the resize events after the resizing is done.  And then you get ten of them,  all one after another,  all for the same (final) window size.

On the one hand,  I like WinGUI's revised handling in situations where redraws are expensive,  because you only have to do one of them,  at the end,  after the user has released the mouse button.  On the other hand,  screen redraws are (in most curses programs) reasonably cheap,  and having the display adjusted each time a column or row is added/removed is easy to do and gives you immediate feedback.

The one thing of which I am absolutely sure here is that the bogus `KEY_RESIZE` events were Just Plain Wrong.  So at least that's gone now...

At least on my Win10 machine,  if you don't "show window contents while dragging",  the new area fills with black,  rather than the bits and pieces of border shown in @loblolly986's display.  (Which is why I never noticed this.)  But you _do_ still get the flood of bogus `KEY_RESIZE`s when you release the mouse button after dragging the window open.

**Comment by loblolly986** [comment]
@Bill-Gray: heh heh, so you're another one who likes the old-school non-"show window contents" style of moving/resizing windows? I like being able to see the starting position when moving or resizing a window. But I doubt most people these days use that mode, and while we may be able to live with the ugliness of the resizing, the average user may think otherwise.

There's also the broader issue here that is the reason for the ugliness: the program (outside of the window procedure) is hung while the window is moved or resized. I could see this being problematic for some programs. From what I see, programs running in a Windows console don't freeze just because the window is moved, so why shouldn't it be the same with WinGUI?

Sorry for the late follow-up. I can report that yes, the default Windows "modal" move/resize implementation is indeed the culprit, and the public-domain "loopless"/modeless implementation by Nathaniel Fries would work as a starting point for a solution.

But there are caveats. The main one is that this approach completely replaces the OS-provided behavior in one's application. So it must emulate the native behavior as closely as possible, which of course can vary a bit across Windows versions. A substantial chunk of Mr. Fries's code is just to emulate the (fluffy) "Aero Shake" and "Aero Snap" features of Windows 7 and later. Which brings up another caveat: this implementation is currently rather incomplete. I fixed a couple bugs while experimenting with it, but while the basic sizing and moving code works well (including with WinGUI), it does not emulate all of the native behavior. It has no implementation of the non-"show window contents while dragging" behavior, so it always functions as if one has that option enabled even if they don't, and moving or resizing through the system menu items is not completely implemented.

There is a better way to correct this issue, though, and I have it working quite nicely on my end. Stand by for a pull request...

**Comment by Bill-Gray** [comment]
> the program (outside of the window procedure) is hung while the window is moved or resized

Ugh.  You'd mentioned that,  but I'd overlooked the consequences.  Run,  for example,  `worm`,  and you get worms moving across the window... except they freeze when you click to drag and stay that way until you release the button.  So yeah,  I'd welcome a fix... good to hear you've got something that looks promising.

Chalk one up for Wine,  though;  it's the only platform I've tried that handles everything correctly.  You get `KEY_RESIZE` events as you change the window size;  the sizes are correct;  the app isn't hung during any of this.  (Which is why this is all news to me.  I don't actually use Microsoft products very much,  and almost never in recent years.)

**Comment by loblolly986** [comment]
Closing this issue because the relevant pull request #170 was merged.

**Comment by Bill-Gray** [comment]
A few notes for possible changes:

If we decide to revert to a single-threaded system,  we can stop the ugly redrawing with the [`SystemParametersInfo` function,  setting `SPI_SETDRAGFULLWINDOWS`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfow) to `false`.  Note that this is a system-wide setting.  When resizing started,  we'd check to see if this parameter was on (by default,  it is),  and shut it off if so.  When resizing ended,  we'd turn it back on.  We can detect those events through the `WM_ENTERSIZEMOVE` and `WM_EXITSIZEMOVE` messages.  Seems straightforward enough... we would still freeze whenever the window was moved/resized,  which seems rather silly.  But I think that would be acceptable,  given the simplification of the code we'd get.

If we are unable to resolve #212,  and/or see other problems arising from the dual-threaded scheme,  I'll be inclined to make this reversion.
