### ISSUE TITLE
Version bump and release?

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#21]
A quick glance showed this is still version 3.4, correct? As it has many changes it would be nice to change the version number. I guess `curses_version()` still says "PDCurses 3.4 - Public Domain 2008", correct?

How can we get the info of the variant used (SDL, win32, win32a...) and important options (wide, utf-8, ...)?

Further: Is there an option to get the version from the header file - if not can you add it (for easy check "xyz should be in" without the need to check every single define and for checking if dll and compilation match together)?

ncurses.h has

```c
/* These are defined only in curses.h, and are used for conditional compiles */
#define NCURSES_VERSION_MAJOR 6
#define NCURSES_VERSION_MINOR 0
#define NCURSES_VERSION_PATCH 20160806

/* This is defined in more than one ncurses header, for identification */
#undef  NCURSES_VERSION
#define NCURSES_VERSION "6.0"

```

And the last one: is there something missing for a puplic release with a tarball (I may missed it)?

**Comment by Bill-Gray** [comment]
On 2016-12-08 16:50, Simon Sobisch wrote:
> A quick glance showed this is still version 3.4, correct? As it has many changes it would be nice to change the version number. What does |curses_version()| says currently?

    It returns the const char *_curses_notice = "PDCurses 3.4 - Public Domain 2008" text,  from initscr.c.

    I started out not really thinking much about version numbers,  because I figured this would all get pulled into wmcbrine/PDCurses.  That seems increasingly unlikely.  So it may be time to change this to PDCurses 4.0 -- Public Domain 2016.

> How can we get the info of the variant used (SDL, win32, win32a...)?

    The longname() function will return a pointer to text such as "PDCurses for SDL",  "PDCurses for X11",  etc.  See line 260 in 'newtest.c' for example use.

> Further: Is there an option to get the version from the header file - if not can you add it (for easy check "xyz should be in" without the need to check every single define and for checking if dll and compilation match together)?

    Um.  That's an interesting question...

    'version.mif' declares ABI_MAJOR=3, ABI_MINOR=4,  VER=34,  VERDOT=3.4.  But I don't see how anything except the makefiles uses that.

    Seems to me we could stand to have,  in curses.h:

#define PDC_MAJOR_VERSION 3
#define PDC_MINOR_VERSION 4
#define PDC_VERSION 304         (hey,  there might be a 3.10 someday)

    With a DLL (or Linux shareable library),  you might wish to ask for the version number of the library.  Or if chtypes are 16,  32,  or 64 bit.  Or if it's 8-bit,  wide char,  or UTF8... I think that's it for variants.

> And the last one: is there something missing for a public release with a tarball (I may missed it)?

    Depends on for what you're looking.  You can go to

https://github.com/Bill-Gray/PDCurses/

    click on "Clone or download",  then "Download ZIP".  That gets you everything that's in the GitHub repo.  I haven't posted libraries,  DLLs,  or executables,  though.

-- Bill

**Comment by GitMensch** [comment]
>  I started out not really thinking much about version numbers, because I figured this would all get pulled into wmcbrine/PDCurses. That seems increasingly unlikely. So it may be time to change this to PDCurses 4.0 -- Public Domain 2016

Sounds good

>> And the last one: is there something missing for a public release with a tarball (I may missed it)?
> Depends on for what you're looking.  You can go to ...

This is a source snapshot, not a release. It isn't necessary at all to provide binaries but it is important to have a fixed version to test against. I suggest the following;

* get the version number change in as soon as possible and add (via a define) "dev" to it
* create a 4.0 milestone at GitHub with a summary of the [planned] changes since the last release (which is PDCurses 3.4 - the release, not the current snapshot)
* create a 4.1 milestone with the things you plan to fix (may be quite empty) and a 5.0 milestone if there are bigger plans that you may want to add in the long run
* do some regression test, check issue list for things solved and important bugs still open and assign them to the milestone, fix them step by step or assign them to a later milestone
* when you are finished:
  * remove the "dev" version addon from master
  * create a 4.0 (or 4.0.0) tag from this version
  * package the tag (either with the "Clone or download" button or otherwise) and publish it
  * bump the version number to 4.1 and add the "dev" addon in master

> The longname() function will return a pointer to text such as "PDCurses for SDL", "PDCurses for X11", etc. See line 260 in 'newtest.c' for example use.

Looks like PDCurses and NCurses have `char * longname (void)`, BSD curses has `void longname (termbuff, char *name)`, saying this is only for resolving the actual terminal name used (which is stored in `ttytype[]` on `initscr()`). But fine, I'll use `char * longname (void)` only if `__PDCURSES__` or ncurses header versions are defined.

To `PDC_MAJOR_VERSION`: yes, this is the way to go, but start with 4.0. If you want to add `PDC_VERSION`, too: use a string and don't care for (sub)versions > 9 - to check for a specific version one should use the single defines.

> Or if chtypes are 16, 32, or 64 bit. Or if it's 8-bit, wide char, or UTF8... I think that's it for variants.

How should this be checked? If compiled a library 16,32,64 bit the OS will check for the same version of the shared library to use it; but if you use 32bit with different`chtypes` than compiled (this is possible, correct?) then the library calls will chrash the memory, correct? How to check this in a library already loaded (and what else should we check "to be safe")? Especially under Windows OS dll's may be floating around and if it doesn't match and the OS doesn't complain you may search for hours for the reason that something doesn't work...

**Comment by GitMensch** [comment]
Rechecked: `longname()` needs a call to `initscr()`, therefore I'll leave this out for the simple command line version information. Good to know about it in any case, may be needed for different parts later.

**Comment by Bill-Gray** [comment]
Hi Simon,

    I see what you mean about release vs. snapshot.  I've dragged my feet for
some time on a "for-real" release,  but you're right;  we shouldn't avoid it too
much longer.  And,  of course,  agreed that this would be 4.0;  I just used 3.4
for example purposes.

    In re longname():  you're right,  this is a little more complicated and
less useful than I thought it would be.  At first,  I thought we could just
revise the PDCurses version so that it works without a call to initscr().
But in ncurses,  we can't,  because ncurses doesn't actually know the
terminal name until the terminal is initialized.  As you say,  it's
referring to the actual terminal,  not the "flavor" of PDCurses.

    Now,  as to library variants:  at present,  with the DLL always given
the name 'pdcurses.dll',  we're asking for trouble.  If you have one app
that requires a PDCurses DLL built for 32-bit Windows,  wide characters,
and 64-bit chtypes,  and another that requires a DLL built for 64-bit Windows,
"legacy" 8-bit characters,  and 16-bit chtypes,  they'll both be looking
for pdcurses.dll.  (With similar issues with shared libraries in Linux/*BSD.)

    I think that both Linux and Windows handle the 32-bit/64-bit OS problems
by putting 32-bit libraries/DLLs in one folder and 64-bit libraries/DLLs in
another.  So when you link the program,  it knows which (for example)
libncursesw.a to link to,  and when you run it,  it knows which libncurses.so
goes with that number of bits.  I've not run into the situation before,  but
will do some investigating.

    Depending on what you'd built or downloaded,  you could then have two
sets of any or all of the following,  one in the 32-bit directory and one
in the 64-bit directory :

pdcurses16.*    (for 16-bit chtypes with 8-bit characters)
pdcurses16w.*   (same,  but for wide characters)
pdcurses16u.*   (same,  for UTF8)
pdcurses32.*    (32-bit chtypes)
pdcurses32w.*   (you see where this is going...)
pdcurses32u.*
pdcurses64.*
pdcurses64w.*
pdcurses64u.*

    where '*' = .a or .so,  or .lib or .dll.

    Actually,  you can scratch pdcurses16w/u;  there's no such animal (can't
represent wide characters of any sort with a 16-bit chtype).  I'd strongly
encourage use of only the UTF8 versions;  anyone assuming 8-bit characters
in 2016 is in a state of perilous sin.  But much use of PDCurses is for
legacy applications,  so I'm not rushing to drop those variants.  (They
aren't that much trouble to support anyway.)

    Note that since the "official" wmcbrine/PDCurses branch uses pdcurses.*,
we can be safe from collisions with it.  (The only issues within that branch
would be if you needed 8-bit,  wide-character,  and UTF8 DLLs;  they would
all get named pdcurses.dll.)

-- Bill

**Comment by GitMensch** [comment]
Hi Bill,

is there any progress in this issue (both the version number defines and the preparation of the 4.0 release)? We're preparing a script for downloading prerequisites including curses and a released release candidate would be a good start for a downloadable reproducible setup.

additional to something like

```c
/* version number for compiler directives */
#define PDCURSES_VERSION_MAJOR 4
#define PDCURSES_VERSION_MINOR 0
```
I'd opt for something like
```c
/* port of PDCurses, mostly for output or check if only some ports are supported by an application */
#define PDCURSES_PORT "win32a"
```
and maybe
```c
/* combined version number (not including any patch level) */
#define PDCURSES_VERSION "4.0"
/* chtype size PDCurses was configured for */
#define PDCURSES_CHTYPE_SIZE 16
```
but as `sizeof(chtype)` should produce the same result we may could drop the later [depending on the compiler this cannot be used in preprocessor stage].

I'd suggest to don't change the binary names - it is a nice option to be able to switch a win32 version with the win32a option and as far as I've understood this it will actually work when they have the same release number.

BTW: If you like to, I'll try to build&run this version of PDCurses on Solaris and old SLES, both TUI only - please drop a note what parts I should build and how to check them.

**Comment by Bill-Gray** [comment]
On 2017-01-06 19:34, Simon Sobisch wrote:
> Hi Bill,
>
> is there any progress in this issue (both the version number
> defines and the preparation of the 4.0 release)?

    None,  I must confess.  True,  I've been busy... but this shouldn't
take much time.  (I wrote that,  then did some investigating and
realized there are nuances I hadn't thought through!)

    At least some of what we're looking for already exists.  I notice
that pdcurses/initscr.c has

const char *_curses_notice = "PDCurses 3.4 - Public Domain 2008";

    which is returned by the curses_version() function in the same file.
We also have the longname() function,  which returns

PDCurses for X11
PDCurses for Win32a
PDCurses for SDL

    ...etc.  In theory,  the Win32a versions can return

PDCurses for Win32a UTF8 DLL
PDCurses for Win32a Wide DLL
PDCurses for Win32a DLL
PDCurses for Win32a UTF8
PDCurses for Win32a Wide
PDCurses for Win32a

     ...depending on how it was compiled.  In practice,  I see that I
bungled the #ifdefs and it always returns plain ol' Win32a.  That's
embarrassing,  though easily fixed.

    Now that I think it through,  I see no good reason for the "DLL" part
anyway.  That's determined at link time;  we already know full well whether
we're linked to a DLL or not.  (And if we're wondering about it at compile
time,  we just check to see if PDC_DLL_BUILD is #defined.)

    The thing we may reasonably want to know at run time is:  was the DLL
we loaded compiled for wide characters,  or UTF-8,  when we really wanted
something else?  So that can be reduced to three cases,  not six.

    The SDL,  X11,  and Win32 console versions can also be dynamically linked,
and can benefit from knowing the character type we're dealing with.

    You're right,  of course,  that we can look at sizeof( chtype) to tell
if we're dealing with a 16-bit,  32-bit,  or 64-bit chtype.  However,  that
doesn't help us to tell the chtype size used by the DLL.  (For similar
reasons,  none of the #defines for version numbers,  etc. will tell us
what the version number of the DLL is.)  So the above needs to be extended
to allow things such as

PDCurses for SDL2 UTF8 32-bit

    The idea is that if you're linking to a DLL and there might be a DLL
Hell mismatch,  you would check

if( strcmp( longname(), "PDCurses for SDL2 UTF8 32-bit"))
     /* show error message */

    to make sure that the DLL is,  generally speaking,  correct.  (You might
also check for Win32a,  if either the Win32a or SDL2 flavors are acceptable
for your app;  in that case,  it's only the UTF8 and 32-bit parts that matter.)

    Then,  to make sure you're using version 4.0 or greater,  you'd use

if( memcmp( curses_version(), "PDCurses 4.0", 12) < 0)
     /* show error message */

> /* version number for compiler directives */
> #define PDCURSES_VERSION_MAJOR 4
> #define PDCURSES_VERSION_MINOR 0

    For that,  we do have (in curses.h)

#define PDC_BUILD 3401

> I'd opt for something like
>
> /* port of PDCurses, mostly for output or check if only some ports are
> supported by an application */
> #define PDCURSES_PORT "win32a"
>
> and maybe
>
> /* combined version number (not including any patch level) */
> #define PDCURSES_VERSION "4.0"
> /* chtype size PDCurses was configured for */
> #define PDCURSES_CHTYPE_SIZE 16

    Given the existence of PDC_BUILD,  longname(),  and curses_version(),  we
may not really need these.  Still,  it might be nice to have something like
the following :

#define PDC_MAJOR_VER 4
#define PDC_MINOR_VER 0
#define PDC_CHANGE_VER 0
#define PDC_VER_YEAR 2017

    These are the only four things we actually change with versions.  This
bit would appear in 'curses.h' :

#define PDC_BUILD (PDC_MAJOR_VER*1000 + PDC_MINOR_VER*100 + PDC_CHANGE_VER)

    And this bit would replace the current _curses_notice in initstr.c :

#define PDC_STR( x) #x
#define PDC_str( x) PDC_STR( x)

const char *_curses_notice = "PDCurses " PDC_str(PDC_MAJOR_VER) "." \
                                          PDC_str(PDC_MINOR_VER) "." \
                                          PDC_str(PDC_CHANGE_VER) " - Public Domain " \
                                          PDC_str(PDC_VER_YEAR);

> but as |sizeof(chtype)| should produce the same result we may could drop
> the later [depending on the compiler this cannot be used in preprocessor stage].

    Yup.  I can't come up with a good reason for a PDCURSES_CHTYPE_SIZE #define,
though as noted above,  a _function_ returning the chtype size with which a DLL
was built might be a good idea.

> I'd suggest to don't change the binary names - it is a nice option to be
> able to switch a win32 version with the win32a option and as far as I've
> understood this it will actually work when they have the same release number.

    Yes,  it should.  With minor caveats.  You can't programmatically resize
an X11 window,  for example,  and the SDL flavors don't support RGB coloring.
Only Win32a supports combining characters and "supplemental plane" Unicode
(Unicode points beyond 64K).  But unless you're using such extended features,
which most people are not,  you can swap libraries freely.

> BTW: If you like to, I'll try to build&run this version of PDCurses on
> Solaris and old SLES, both TUI only - please drop a note what parts I
> should build and how to check them.

    That might indeed prove interesting...

    I've occasionally meant to do some work on better testing procedures for
this code.  At present,  I mostly just run 'newtest' and 'testcurs' and verify
that they appear to run sanely.  (Which is certainly a good first step.)  A
full test would get _very_ detailed indeed,  involving trying different
keyboards,  Asian languages,  and some of the more obscure parts of PDCurses
that I don't even really know about;  I mostly focussed on the bits described
in IMPLEMNT.md and the bits needed to get my own code working.

    If you do give it a try,  I'd want to know of any bugs you encountered.  It
may not be worth doing a full-fledged testing run,  though.

-- Bill

**Comment by GitMensch** [comment]
OK, I'll do the simple test you've mentioned with a simple git download.

Concerning the "check what exact version was used during compile": Instead of an strcmp I'd suggest to create a small structure with the important bits and pass it, something like

```c
/* Perform type */
enum pdc_port {
	PDC_PORT_X11 = 0,
	PDC_PORT_WIN32,
	PDC_PORT_WIN32A,
	[...]
};

/* Detailed PDC version information */
struct pdc_version_info {
	const char		*name;		/* Similar to longname, without the need for initscr */
	const int	chtype_syize;
	const enum pdc_port port;
	[...]
};
```

This way you can really check and check simple and reliable for the things you want to know - which in any case would only be available with `#if defined(PDC_MAJOR_VER) && PDC_MAJOR_VER >= 4`.

BTW: I'd advise to use the category first --> instead of `PDC_MAJOR_VER` use `PDC_VER_MAJOR`.

**Comment by Bill-Gray** [comment]
Hi Simon,

    As you'll see,  I've just pushed changes implementing at least some
of this.

    Specifically,  defines for PDC_VER_MAJOR,  PDC_VER_MINOR,  PDC_VER_CHANGE,
and PDC_VER_YEAR are now in curses.h.  These are 4, 0, 0, and 2017,  respectively.
The existing PDC_BUILD constant (was 3401,  i.e. version 3.4.01) is computed
from this,  and is now equal to 4000.  Similarly,  the curses_version()
string is built using the new macros.  The 'newtest' demo,  if dragged open
a few extra lines,  now shows the curses_version string.

    You made a comment about "similar to longname(),  but without the need to
call initscr() first".  I've revised things so you can,  in fact,  call
longname() before initscr() now.  As noted in the commit message,  this is
a PDCurses-only sort of thing.  In ncurses,  there's no way to know what sort
of terminal you're using until you've initialized it.

    This does not (yet) address the DLL checking issue.  For that,  I'll
probably do something quite similar to your 2017 Jan 8 thoughts,  with a small
structure giving the relevant bits.  Obviously,  this does pave the way for
those changes.

    (The latest pushed commits also implement a makefile so one can build the
demos against ncurses.  I'm curious about this as a way of demonstrating the
differences between ncurses and PDCurses;  I'd like the demos to make
PDCurses-specific behavior more apparent.  I also fixed a bug reported by
Màrio Montes where some numeric keypad hits caused two characters to be returned.)

-- Bill

**Comment by GitMensch** [comment]
Sounds good, please drop a note as soon as you've added the structure as I wait for making PDC_BUILD 4000 changes to GnuCOBOL until then.

**Comment by Bill-Gray** [comment]
Just pushed an update that includes a 'PDC_version' structure,  and a demo snippet 'version.c' showing how the version can be checked without reference to initscr() or the rest of Curses :

https://github.com/Bill-Gray/PDCurses/commit/08fd141dc649899af823ff868ad4e594e4d78d80

**Comment by GitMensch** [comment]
This looks nice, will give it a try, likely sometime this week.
I assume you have anything in order to do publish a 4.0.0 release candidate, don't you? If not it would be nice (and likely not unpractical for you) to create a 4.0.0 milestone and add the tickets to it that you want to get solved beforehand.

**Comment by GitMensch** [comment]
Ping after > 6 months: 4.0 release candidate? As people highlighted about GnuCOBOL "there is always something to improve but people should not be stuck for using either an outdated version or a development snapshot" (we just pushed a final release candidate and likely will get out the final next week).

If there are no show stoppers (reading as "something that always worked before doesn't worked any more") I want to encourage you to do a release. win32a is "new" and even if something doesn't work there (for example cyginw/mingw issues - if they still exists) it would be no show stopper and as "old" code parts where improved, too a new release will be helpful for the other variants, too.

**Comment by GitMensch** [comment]
For `const PDC_version_info PDC_version;` VS raises get the warning message:

> `curses.h(419): warning C4132`

> 'object' : const object should be initialized
> The constant was not initialized.
> Because the value of a symbol with the const attribute cannot be changed after its definition, it should be given an initialization value.
> It will not be possible to assign a value to object.

**Comment by GitMensch** [comment]
I've removed the `const`, see https://github.com/Bill-Gray/PDCurses/pull/51

**Comment by GitMensch** [comment]
Do you see any show stoppers for a release (or at least release candidate)?

If not I'd encourage you to wait 1-2 days if @jwinarske finishes the additional CMake stuff in https://github.com/Bill-Gray/PDCurses/pull/52 to include it (and include the generated VS files *in the release windows source zip) and get it out. Thoughts?

**Comment by GitMensch** [comment]
@Bill-Gray Ping pong pung ...

**Comment by Bill-Gray** [comment]
OK,  just gave it a try... as I should have realized,  GitHub provides excellent docs on how to create and edit releases.  I first gave it a try on a project nobody's watching,  then tried it here,  and still managed to get it wrong;  apologies if people got a flurry of pointless notifications.

Anyway,  I think it's all good now,  and  we have a 4.0.2 release.

**Comment by GitMensch** [comment]
Wonderful!
Please change the tag's description, ideally including the changelog since 3.4 (at least the highlights including new win32a variant) at https://github.com/Bill-Gray/PDCurses/releases/tag/v4.0.2
I'm not sure but you may *could* add me to the developers (not sure if I could change this then)...

**Comment by GitMensch** [comment]
OK, I'm starting updating the release list (including the old versions). But actually there are *no* entries in HISTORY.md for PDCurses 4.0.2 - Do you add these or should I do so, too? If we change the file (which I'd highly suggest) I'd also suggest to re-create the 4.0.2 release (with only this addition). Thoughts?

BTW: I'd like to share the information on the release on different places, are you OK with this (you may want to do so yourself)?

**Comment by GitMensch** [comment]
@Bill-Gray : the [release list][1] is complete now, concerning all versions down to 2.5 (there aren't older tags). The [4.0.2 release notes][2] are quite empty as there was no entry in [HISTORY.md][3] in. Can you update this file (see my previous note)?

[1]:https://github.com/Bill-Gray/PDCurses/releases
[2]:https://github.com/Bill-Gray/PDCurses/releases/tag/v4.0.2
[3]:https://github.com/Bill-Gray/PDCurses/blob/master/HISTORY.md

**Comment by Bill-Gray** [comment]
@GitMensch : thank you,  looks great... I'll revise HISTORY.md to mention what's happened between 3.4 and 4.0.2, set the release notes accordingly,  and redo the 4.0.2 release.  Should be quite a long set of notes,  even just hitting the high points.

In re sharing info on the release,  please go ahead.  This is all quite "public" as far as I'm concerned.

**Comment by GitMensch** [comment]
Please drop a note when you are ready with the HISTORY entry.

**Comment by GitMensch** [comment]
@Bill-Gray I've minimally tweaked the HISTORY entry and updated the release information accordingly to your changes. Furthermore I've created the User Guide with `cd doc && make` and added it to the release (after converting to PDF via markable.in we should replace it with a nicer style, the only good one I've found has SPAM links in...)

So I'd say this issue can finally be closed.
