### ISSUE TITLE
X11: Crash on mouse selection -- solution

### ISSUE THREAD

**Issue by klamonte** [Bill-Gray/PDCurses#26]
I discovered for qodem that the XCursesButton() function is sometimes called with a button number value (event->xbutton.button) of 0x7F00.  I do not understand why, as that should be impossible, but it causes the "save_mouse_status.button[button_no - 1]" on line 2412 to reference an invalid address and thus crash the X11 process.  For my branch, the fix was to add a check immediately after:

    button_no = event->xbutton.button;

...to:

    button_no = event->xbutton.button;
    if ((button_no < 0) || (button_no > 5)) {
        button_no = 0;
    }

(This all around line 2294 in x11.c.)

Giving this one to you, if you'd like to PR it to wmcbrine you can.

**Comment by Bill-Gray** [comment]
Hi Kevin,

    Well,  _that's_ odd...

    I'll see if I can figure it out.  I am no Xlib expert;  the fact
that we're getting out-of-range buttons may be telling us something.
If I can't figure out why it's happening,  I'll give up and just apply
this fix.  Thanks for passing this along.

    The code _does_ have the ability to handle up to nine buttons.
I used to have a gaming mouse with seven button,  which I used for
testing.  However,  I don't think the X11 version is currently set up
for more than five.  We probably still need your fix,  in case
somebody sets up a gaming mouse and hits the sixth button.

-- Bill

**Comment by Bill-Gray** [comment]
OK,  made a little progress here...

    Limiting the number of buttons to five is a problem,  for
several reasons.  First,  the array in question has only
three elements,  so that,  not five,  is the real limit.

    Buttons 4 and 5 are used for wheel mice.  6 and 7 are
used for 'tilt wheel mice' (see lines 2329-2333).  It doesn't
look as if those buttons cause trouble in the MotionNotify code.
But I tried a mouse with an extra button that produces
button_no = 9 (no idea where button_no = 8 went) and sure enough,
that got passed to the MotionNotify code.  (Without breaking
anything.  I assume that for smaller button numbers,  you can
look past the end of the array without causing a crash.  It's
when you look for button 0x7F00,  as you did,  that a crash
conveniently makes the underlying bug obvious.)

    Looking elsewhere in the code,  it seems to me that efforts
are made to make sure we access button elements 0,  1,  or 2,
without going outside the array.  I need to check that a little
more carefully,  though... some of this code is a little more
opaque than one might wish.

    We do,  of course,  still have the puzzle of what a button
number 0x7f00 is all about.

-- Bill

**Comment by klamonte** [comment]
Yup, looks like it really is 1-3 and not 1-5.  But peeking past 3 just modifies the changes field in MOUSE_STATUS, so no crash.

How is the SDL2 backend coming along?  Is it feature complete now?  I'm tempted to just support that and abandon the separate X11/Win32a backends.

**Comment by GitMensch** [comment]
@Bill-Gray is this fixed with your use of wmcbrine's X11 version?

**Comment by Bill-Gray** [comment]
@GitMensch I don't really know that it has.  I'm not seeing the error,  and the code has been quite heavily revised,  so I think this is a bug that applies to code we no longer have.
I'll close this issue.  But (see above) I've added an `assert()` to check that the button number is in the correct range.  If that trips,  we may have to re-open this issue.
