### ISSUE TITLE
win32a variant (MINGW): failing "manual" tests

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#36]
testcurs.exe:
- Intro[X] 
- Pad Test[ ]  (the truncations and "should not appear" don't work)
- Rezise Test[X]  (while it would be good to be able to resize it with the mouse, too)
- Scroll Test[X]
- Input Test[X]
- Output Test[X]
- ACS Test[X]  (while it shows a line break for ACS_WHITE_BULLET which likely shouldn't be in there - maybe make the size of the window bigger?)
- Color Test [X]

Recognized in testcurs.exe:
* Output test says "this terminal claims to support blinking" but the `BLINK` items in the Color test aren't blinking
* testcase Output - we may want to finish the test with PADENTER, too (in any case it is recognized in the Input test)
* resizing via mouse doesn't work
* marking with the mouse (for copy) doesn't work as it always returns an event and the tests go on, as we have "Paste" in the menu already: can I suggest to add a "Mark" entry?

**Comment by Bill-Gray** [comment]
Just to check:  are you running Win32a or Win32?

In re Pad Test:  I think this is a failure in the logic for the test,  rather than a problem in the underlying PDCurses functions.  It works the same way in all flavors,  _and_ (somewhat crucially) when linked with `ncurses`.  The wording a little weird,  and I'm not sure what the test is really supposed to do.

In re ACS Test:  by coincidence,  I was looking at that problem this morning.  It's supposed to work for any size window,  adding/removing columns according to the width of the window.  I think I now have it doing so correctly (changes not yet pushed),  with the code looking a little easier to follow as well.

In re the lack of blinking:  by default,  blinking is shown as just a difference in intensity:

https://projectpluto.com/win32a.htm#2010apr13

Run `testcurs -b` to get for-real blinking.  (Actually,  I notice that this works with Win32a,  but not with Win32.  A quick bit of searching suggests you can't get blinking in a Win32 console.  I vaguely recall that `testcurs -b` worked properly in DOS as well.)

Further checking shows that when `testcurs` says "claims to support blinking",  they mean "set the blink attribute and something visible happens".  The only way to find out if you can actually get blinking text is to call `PDC_set_blink` and check the return value.  Which wouldn't be a bad test to run.

Mouse resizing doesn't work on Win32 (or DOS).  It should work on Win32a (and SDLx and X11).

**Comment by GitMensch** [comment]
> Just to check: are you running Win32a or Win32?

Both for comparison. This issue is about `win32a`.
Using `testcurs -b` does real blinking. I think we may add the call to `PDC_set_blink( )` in GnuCOBOL (conditionally on an environment variable). Is the option to turn this on/off something specific to PDCurses, this branch or even win32a? If yes it would be good to provide an environment variable to switch the default option within PDCurses.

Mouse resizing does definitely not work in testcurs,exe or worm.exe in Win32a neither on Cygwin nor on Mingw.

**Comment by Bill-Gray** [comment]
`PDC_set_blink()` is specific to PDCurses (exists in "mainstream" PDCurses and in this branch).  As the PDC prefix indicates,  you won't find it in ncurses.

"Real" blinking (as opposed to just setting a high-intensity display) will work in Win32a,  X11,  and (usually) in DOS and OS/2.  It fails on SDLx and Win32 console.  It may work someday for SDLx,  if somebody takes on that project and adds a timer (probably won't be me.)  I don't see how it would be done for Win32,  unless one set up a separate thread to handle the console drawing... basically,  the sort of thing that's done in X11.

I see what you mean about the resizing.  I'd forgotten that some time ago,  we disabled resizing by default.  The problem was that a lot of programs were written assuming 25 lines and 80 columns,  and would get hopelessly confused if you tried to resize them.  So a program has to deliberately turn resizing on,  effectively saying,  "Yes,  I'll handle the KEY_RESIZE key events if they happen."  (Or will check `is_termresized()` as needed.)  I will add comments on that tomorrow... time for me to sleep!

**Comment by GitMensch** [comment]
Retested with cygwin64: ACS test is fine now (shows the complete text and the additional output of the PDC version is nice (although I think it should be on the main testcurs screen - NOT in the ACS test), but 41bcf1b seems to not work as expected, testcurs can still not be manually resized.

**Comment by GitMensch** [comment]
Just a ping @Bill-Gray here to be possibly able to close one of the oldest open issues - does it work for you in your test envrionments for wWinGUI?

**Comment by Bill-Gray** [comment]
Yup,  should've fixed this a while back... as you'll see,  it wasn't a major fix.  (Though maybe it would have been three years back... I don't remember when I added resizing limits.)

General note that it's still the case that we default to WinGUI screens being non-resizable,  on the theory that a lot of older programs won't handle resizing properly anyway,  and those that do can just call `PDC_set_resize_limits()`.  (Or,  if they just want a fixed size that isn't 25x80,  they can call `resize_term()` before `initscr()`.)

Also,  just reread your note from 2017 May 8 that it would be nice to have the added ACS test data, 
```
   PDCurses 4.1.99 - Jul 11 2020
   sizeof( chtype) = 8; sizeof( mmask_t) = 4
```
shown on the main `testcurs` screen instead.  To which I would add the platform,  such as "PDCurses for WinGUI",
and "Wide" and "UTF8" if those are defined.   There's a good bit of room at the bottom of the main screen.
