### ISSUE TITLE
removing gccwin32.mak, maybe renaming mingwin32.mak

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#40]
As discussed in #12 and others the gccwin32.mak seems not not be needed any more, mingwin32.mak is thought to compile under cygwin, msys(2) [shell and GNU tools for Mingw32/64) *so far tested*, cross-compilation from GNU/Linux (please publish some notes when testing this how to setup this) and with a "plain" Mingw based compiler from cmd/Powershell (this test is open, too).

When these are finished the old gccwin32.mak can be deleted - but we should think about renaming mingwin32.mak to something more generic or even to gccwin32.mak (all these built environments above use GCC for compilation to (and in most cases on) win32).

**Comment by Bill-Gray** [comment]
I do think we're closing in on getting rid of the current gccwin32.mak;  should be able to delete it once the various tests you mention are done.  (I cross-compile from Linux most of the time,  but test by compiling with plain old MinGW from `cmd` on Windows 8 and Windows ME.  That last is actually a pretty important test,  since PDCurses gets used on legacy systems.

As you say,  the name 'mingwin32.mak' is becoming a little misleading.  I'd not be totally happy with renaming it to 'gccwin32.mak',  but would at least agree it's slightly less misleading.

**Comment by GitMensch** [comment]
Done already.
