### ISSUE TITLE
Unable to unsubscribe from email notifications

### ISSUE THREAD

**Issue by xucaen** [Bill-Gray/PDCurses#54]
I have tried unfollowing the project, blocking the project as even flagging emails as spam yet your emails continue to flood my inbox. Please forcibly remove me from your mailing lists. Much appreciated.

**Comment by Bill-Gray** [comment]
Hi James,

   I don't think I can unsubscribe you.  As best I can tell,  in general,  nobody can unsubscribe somebody else (including me as the maintainer of this fork of PDCurses.)

   With the warning that I've never run into the situation myself... the following may help:

https://help.github.com/articles/unsubscribing-from-conversations/
https://github.com/settings/emails

   Re the first link:  I do see an 'Unsubscribe' button,  with the notice "You're receiving notifications because you're subscribed to this repository" (are you seeing that?)  The second link should be used if you're just trying to get rid of all GitHub notifications,  not just PDCurses-related ones.

   This third link suggests you're not the only one having problems getting rid of unwanted GitHub notifications.  Unfortunately,  it doesn't propose any solutions that appear to have worked:

https://webapps.stackexchange.com/questions/43096/stop-receiving-github-notifications

**Comment by GitMensch** [comment]
Please close the issue - it is a completely GitHub only related issue and has nothing to do with this project.
Note: GitHub staff actually does a nice mail support (if "Help" in the bottom left links doesn't work use "Contact GitHub" in the bottom right).

**Comment by techtonik** [comment]
@xucaen - there is a button to the right to unsubscribe from specific issues. If that won't help, forward message to GitHub support.

**Comment by Bill-Gray** [comment]
I'm assuming James has fixed this one way or another and am closing the issue.
