### ISSUE TITLE
SDL2 fixes missing?

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#86]
Please have a look at https://github.com/wmcbrine/PDCurses/commits/master/sdl2, at least since May 2018

**Comment by Bill-Gray** [comment]
Yup,  I'd like to have those changes.  Plus many that have been made to the Windows console flavor to make resizing more stable and to add blink,  bold,  and (I think) italic fonts.  And a few miscellaneous changes that have occurred in the wmcbrine version since it "came to life" in early 2018.

Unfortunately,  this fork has drifted enough from its wmcbrine ancestry that a fair bit of hand work will be required to get it all moved in.  I expect it'll happen,  but if it's me doing it,  it probably won't be very soon.

**Comment by GitMensch** [comment]
@Bill-Gray: Do you have any idea what "won't be very soon" means?
Do you see any option to create a new release (maybe including this)? The vt variant seems to be working enough to be released as a test version doesn't it?

**Comment by GitMensch** [comment]
@Bill-Gray this is solved by your last merges, isn't it?

**Comment by Bill-Gray** [comment]
True,  fixes added by essentially copying @wmcbrine's work (almost) byte-for-byte.
